version: "3.7"
services:
  app:
    build:
      args:
        user: adidash
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: adidash
    container_name: adidash-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - adidash

  db:
    image: mysql:5.7
    container_name: adidash-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - adidash

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_ARBITRARY: "0"
    networks:
      - adidash

  nginx:
    image: nginx:alpine
    container_name: adidash-nginx
    restart: unless-stopped
    ports:
      - 8000:443
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
      - ./docker-compose/nginx-ssl:/etc/nginx/ssl/
    networks:
      - adidash
networks:
  adidash:
    driver: bridge
